name: build

on: [workflow_dispatch, push]

env:
  PKG_NAME: "http-echo"
  EXO_REGISTRY: exo.container-registry.com
  EXO_REPO_NAME: panop/http-echo


jobs:
  get-go-version:
    name: "Determine Go toolchain version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - uses: actions/setup-go@v4 # v4.1.0
        with:
          # This is the minimum required version. Go 1.21+ should pull in new 
          # toolchains as indicated in go.mod.
          go-version: '1.24'
      - name: Determine Go version
        id: get-go-version
        # With go1.21+, we can use `go version` to print out the exact toolchain that will be used
        run: |
          echo "Building with Go $(go version | awk '{print $3}' | sed -e 's/^go//')"
          echo "go-version=$(go version | awk '{print $3}' | sed -e 's/^go//')" >> $GITHUB_OUTPUT

  set-product-version:
    runs-on: ubuntu-latest
    outputs:
      product-version: ${{ steps.set-product-version.outputs.product-version }}
      product-base-version: ${{ steps.set-product-version.outputs.base-product-version }}
      product-prerelease-version: ${{ steps.set-product-version.outputs.prerelease-product-version }}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - name: Set Product version
        id: set-product-version
        uses: hashicorp/actions-set-product-version@v1

  generate-metadata-file:
    needs: set-product-version
    runs-on: ubuntu-latest
    outputs:
      filepath: ${{ steps.generate-metadata-file.outputs.filepath }}
    steps:
      - name: "Checkout directory"
        uses: actions/checkout@v3 # v3.5.3
      - name: Generate metadata file
        id: generate-metadata-file
        uses: hashicorp/actions-generate-metadata@v1
        with:
          version: ${{ needs.set-product-version.outputs.product-version }}
          product: ${{ env.PKG_NAME }}
          repositoryOwner: "docksify"
          repository: "http-echo"
      - uses: actions/upload-artifact@v4
        with:
          name: metadata.json
          path: ${{ steps.generate-metadata-file.outputs.filepath }}

  build-docker-default:
    name: Docker ${{ matrix.arch }} default release build
    needs:
      - set-product-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
    env:
      repo: ${{ github.event.repository.name }}
      version: ${{ needs.set-product-version.outputs.product-version }}

    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - name: Log in to Exoscale Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.EXO_REGISTRY }}
          username: ${{ secrets.EXOCR_USER }}
          password: ${{ secrets.EXOCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ${{ env.EXO_REGISTRY }}/${{ env.EXO_REPO_NAME }}:latest
          
