name: build

on: [workflow_dispatch, push]

env:
  PKG_NAME: "http-echo"
  EXO_REGISTRY: exo.container-registry.com
  EXO_REPO_NAME: panop/http-echo


jobs:
  build-docker-default:
    name: Docker ${{ matrix.arch }} default release build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]

    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - name: Log in to Exoscale Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.EXO_REGISTRY }}
          username: ${{ secrets.EXOCR_USER }}
          password: ${{ secrets.EXOCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ${{ env.EXO_REGISTRY }}/${{ env.EXO_REPO_NAME }}:latest
          
